imports_layout = "Mixed"
imports_indent = "Block"
match_block_trailing_comma = true
merge_imports = true
normalize_comments = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
struct_field_align_threshold = 20
wrap_comments = true
format_strings = true
hard_tabs = true
newline_style = "Unix"
use_field_init_shorthand = true
